<% project_name = 'yamba-api' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: yamba-api_development

test:
  <<: *default
  database: yamba-api_test
